### ISSUE TITLE
Add HA tests

### ISSUE THREAD

**Issue by displague** [equinix/terraform-metal-multiarch-k8s#112]
Current examples/simple only tests a single control plane. Before the move to test examples/simple, when testing was run from the root directory, HA tests were defined but not passing (removed in https://github.com/equinix/terraform-metal-multiarch-k8s/pull/98/commits/96fc17eaf5f4c6e91bdf211e92289a830c21e4ad).

The workflow configuration would look like this:

```
    - name: HA Terraform Plan
      id: ha-plan
      timeout-minutes: 45
      env:
        TF_VAR_control_plane_node_count: 2
      run: terraform plan -out=tfplan -input=false
    - name: HA Terraform Apply
      id: ha-apply
      timeout-minutes: 45
      run: terraform apply -input=false tfplan
    - name: HA Terraform Destroy
      id: ha-destroy
      if: ${{ always() }}
      run: terraform destroy -input=false -auto-approve
```
